#!/bin/bash
echo 177695 | sudo -S bash -c '
LFS=/home/lfs/lfs-root

echo "=== Copy built pkg-config files from /usr/lib64 ==="
mkdir -p "$LFS/usr/lib/pkgconfig"
for f in /usr/lib64/pkgconfig/*.pc; do
    [ -f "$f" ] || continue
    bn=$(basename "$f")
    cp -f "$f" "$LFS/usr/lib/pkgconfig/$bn" 2>/dev/null
    echo "  $bn"
done

echo "=== Copy protocol files ==="
# Generate Hyprland protocol files
cd /tmp/build/Hyprland-0.30.0
mkdir -p protocols
# The protocols need to be generated by wayland-scanner
for proto in hyprland-global-shortcuts-v1; do
    src_xml="/usr/share/wayland-protocols/hyprland/$proto.xml"
    if [ ! -f "$src_xml" ]; then
        # Check subprojects
        find . -name "*$proto*" -type f 2>/dev/null
    fi
done

echo "=== Fix wlroots wayland version ==="
# The host wayland-server.pc has version 1.20.0, we need 1.22.0
# The built one should override - check where it installed
ls /usr/lib64/pkgconfig/wayland-server.pc 2>/dev/null && cat /usr/lib64/pkgconfig/wayland-server.pc | head -5
'
